import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import ErrorButton from '@/components/ErrorBoundary/ErrorButton/ErrorButton';
import Search from '@/components/Search/Search';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fav_icon.svg" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
        <Search disabled={false}/>
          <ErrorButton />
        </div>

        <div className={styles.center}>
        </div>
      </main>
    </>
  );
}
