import { useAppDispatch, useAppSelector } from '@/store/hooks';
import styles from '@/styles/Home.module.css';
import React from 'react';
import { changeAllPage } from '@/store/mainPageSlice';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { ReactNode } from 'react';
import ErrorButton from '@/components/ErrorBoundary/ErrorButton/ErrorButton';
import CardsSection from '@/components/CardsSection/CardsSection';
import Search from '@/components/Search/Search';
import Pagination from '@/components/Pagination/Pagination';
import { Cards, IResponseApi } from '@/types/interfaces';
import { checkRouterElement } from '@/utils/functions';

type LayoutProps = {
  children?: ReactNode;
  data: IResponseApi;
};

const Layout = ({ children, data }: LayoutProps) => {
  const cardsdata: Cards = data.results ? data.results : [];

  const dispatch = useAppDispatch();

  dispatch(changeAllPage(data.info.pages));
  const numPerpage = useAppSelector((state) => state.mainPage.numPerpage);
  const router = useRouter();
  const { page, name } = router.query;
  const href = name
    ? {
        pathname: '/',
        query: {
          page: page || '1',

          search: name || '',
        },
      }
    : {
        pathname: '/',
        query: {
          page: page || '1',
        },
      };
  const redirectToMain = () => {
    if (router.pathname === '/details/[id]') {
      router.push(href);
    }
  };

  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/fav_icon.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description} onClick={redirectToMain}>
          <Search disabled={false} />
          <ErrorButton />
        </div>
        <CardsSection cardsdata={cardsdata.slice(0, numPerpage)} />
        <Pagination
          currentPage={parseInt(checkRouterElement(page, '1'))}
        ></Pagination>

        {children}
      </main>
    </>
  );
};

export default Layout;
